"""screencast.compose tests.

test_view_at_* cover the composer's core policy (screencast.compose._view_at)
as pure functions -- no ffmpeg involved. test_compose_* run the real
composer against tiny synthetic clips generated by ffmpeg's own lavfi
source, skipped when ffmpeg/ffprobe aren't on PATH (this repo's CI has them
via devenv.nix's ffmpeg-headless package; a plain checkout may not)."""

from pathlib import Path
from screencast import compose as compose_module
from screencast.compose import _output_time
from screencast.compose import _view_at
from screencast.compose import compose
from screencast.compose import ComposeError
from screencast.compose import ffprobe_duration
from screencast.compose import write_captions_vtt
from screencast.timeline import Timeline
from screencast.verify import parse_vtt_cue_times
import pytest
import shutil
import subprocess


# (turn_id, actor, start, end) -- turn_id, not actor name, is what _view_at
# keys its return value on: an actor with more than one turn (e.g.
# "reception" in contact_form.robot) gets one entry per turn here, never
# collapsed to their last one. See test_compose_uses_every_turns_own_clip_*
# below for the full-composer regression case this shape exists for.
TURNS = [(0, "author", 1.0, 3.0), (1, "reviewer", 5.0, 8.0)]


def test_before_any_turn_observer_is_main_with_no_inset():
    view, turn_id, *_ = _view_at(0.5, [], TURNS)
    assert (view, turn_id) == ("observer", None)


def test_inside_a_turn_the_actor_is_main_by_default():
    view, turn_id, *_ = _view_at(2.0, [], TURNS)
    assert (view, turn_id) == ("actor", 0)


def test_focus_flips_main_inside_a_turn():
    focus = [{"time": 1.5, "view": "observer", "scale": 0.4, "margin": 24, "border": 3}]
    view, turn_id, *_ = _view_at(2.0, focus, TURNS)
    assert (view, turn_id) == ("observer", 0)


def test_a_focus_event_from_an_earlier_turn_does_not_leak_into_a_later_turn():
    focus = [{"time": 1.5, "view": "observer", "scale": 0.4, "margin": 24, "border": 3}]
    view, turn_id, *_ = _view_at(6.0, focus, TURNS)
    assert (view, turn_id) == ("actor", 1)


def test_gap_after_a_turn_defaults_to_observer_with_frozen_actor_inset():
    view, turn_id, *_ = _view_at(4.0, [], TURNS)
    assert (view, turn_id) == ("observer", 0)


def test_gap_focus_event_can_bring_back_the_actor():
    focus = [{"time": 3.5, "view": "actor", "scale": 0.4, "margin": 24, "border": 3}]
    view, turn_id, *_ = _view_at(4.0, focus, TURNS)
    assert (view, turn_id) == ("actor", 0)


REPEATED_ACTOR_TURNS = [
    (0, "reception", 0.0, 2.0),
    (1, "specialist", 3.0, 5.0),
    (2, "reception", 6.0, 8.0),
]


def test_a_repeated_actors_two_turns_resolve_to_their_own_turn_id():
    """(regression, PR #14 review finding #2) Keying by actor name instead
    of turn_id would make both of "reception"'s turns resolve to whichever
    turn a dict happened to keep last."""
    view, turn_id, *_ = _view_at(1.0, [], REPEATED_ACTOR_TURNS)
    assert (view, turn_id) == ("actor", 0)
    view, turn_id, *_ = _view_at(7.0, [], REPEATED_ACTOR_TURNS)
    assert (view, turn_id) == ("actor", 2)


ffmpeg_available = shutil.which("ffmpeg") and shutil.which("ffprobe")
requires_ffmpeg = pytest.mark.skipif(
    not ffmpeg_available, reason="ffmpeg/ffprobe not on PATH"
)


def make_clip(path, duration, color="blue"):
    subprocess.run(
        [
            "ffmpeg",
            "-y",
            "-v",
            "error",
            "-f",
            "lavfi",
            "-i",
            f"color=c={color}:s=320x180:d={duration}:r=25",
            str(path),
        ],
        check=True,
    )


# Named ffmpeg colors, as 8-bit RGB -- used to check a sampled corner pixel
# against the clip color that should (or should not) be composited there.
_NAMED_COLOR_RGB = {
    "blue": (0, 0, 255),
    "red": (255, 0, 0),
    "yellow": (255, 255, 0),
    "magenta": (255, 0, 255),
}


def corner_pixel(video, at, corner, offset=100, size=40):
    """Average RGB of a small sample square inward from the given corner at
    `at` seconds -- used to check whether (and which) PiP inset is visible
    there. Sampled `offset` px in from both near edges (not at the literal
    0/0 corner), since an inset's own box starts `margin` px in from the
    frame edge -- a sample at the exact pixel corner would land partly on
    background instead of inside the inset."""
    crop = {
        "bottom-left": f"{size}:{size}:{offset}:ih-{offset + size}",
        "bottom-right": f"{size}:{size}:iw-{offset + size}:ih-{offset + size}",
        "top-left": f"{size}:{size}:{offset}:{offset}",
        "top-right": f"{size}:{size}:iw-{offset + size}:{offset}",
    }[corner]
    result = subprocess.run(
        [
            "ffmpeg",
            "-v",
            "error",
            "-ss",
            f"{max(0.0, at):.3f}",
            "-i",
            str(video),
            "-frames:v",
            "1",
            "-vf",
            f"crop={crop},scale=1:1",
            "-f",
            "rawvideo",
            "-pix_fmt",
            "rgb24",
            "-",
        ],
        check=True,
        capture_output=True,
    )
    data = result.stdout
    assert len(data) >= 3, f"Could not sample a frame at {at:.2f}s from {video}"
    return tuple(data[:3])


def is_color(pixel, name, tol=60):
    target = _NAMED_COLOR_RGB[name]
    return all(abs(p - t) <= tol for p, t in zip(pixel, target, strict=True))


@requires_ffmpeg
def test_compose_a_simple_take_produces_a_valid_output(tmp_path):
    take_dir = tmp_path / "take"
    take_dir.mkdir()
    make_clip(take_dir / "observer.webm", 6.0)
    make_clip(take_dir / "author.webm", 2.0, color="red")

    timeline = Timeline.new("observer.webm")
    timeline.add_actor_clip("author", "author.webm", offset=1.0, duration=2.0)
    timeline.add_event({"type": "turn_start", "time": 1.0, "actor": "author"})
    timeline.add_event({"type": "turn_end", "time": 3.0, "actor": "author"})
    timeline.save(take_dir / "timeline.json")

    output = compose(take_dir)
    assert output.exists()
    assert ffprobe_duration(output) == pytest.approx(6.0, abs=0.5)


@requires_ffmpeg
def test_compose_with_chapter_and_hold_extends_output_duration(tmp_path):
    take_dir = tmp_path / "take"
    take_dir.mkdir()
    make_clip(take_dir / "observer.webm", 3.0)
    make_clip(take_dir / "author.webm", 1.0, color="red")

    timeline = Timeline.new("observer.webm")
    timeline.add_actor_clip("author", "author.webm", offset=0.5, duration=1.0)
    timeline.add_event({"type": "turn_start", "time": 0.5, "actor": "author"})
    timeline.add_event(
        {
            "type": "chapter",
            "time": 0.5,
            "eyebrow": "Story",
            "title": "Author",
            "subtitle": "Doing a thing",
            "duration": 2.0,
        }
    )
    timeline.add_event({"type": "turn_end", "time": 1.5, "actor": "author"})
    timeline.add_event({"type": "hold", "time": 3.0, "duration": 1.5})
    timeline.save(take_dir / "timeline.json")

    output = compose(take_dir)
    # 3.0s of real footage + 2.0s inserted title card + 1.5s inserted hold.
    assert ffprobe_duration(output) == pytest.approx(6.5, abs=0.5)


@requires_ffmpeg
def test_compose_does_not_extend_output_for_a_recorded_hold(tmp_path):
    """(regression, PR #14 follow-up review) A "recorded" hold marks real
    elapsed recording time (e.g. the return-to-observer wait) -- unlike an
    ordinary Hold, the composer must not insert an extra synthetic freeze
    for it, since that time is already part of the observer's own footage."""
    take_dir = tmp_path / "take"
    take_dir.mkdir()
    make_clip(take_dir / "observer.webm", 5.0)

    timeline = Timeline.new("observer.webm")
    timeline.add_event({"type": "hold", "time": 3.0, "duration": 1.5, "recorded": True})
    timeline.save(take_dir / "timeline.json")

    output = compose(take_dir)
    # No inserted title card, no synthetic freeze -- just the 5.0s of real
    # observer footage the "recorded" hold's own window is already part of.
    assert ffprobe_duration(output) == pytest.approx(5.0, abs=0.5)


@requires_ffmpeg
def test_compose_is_reproducible_from_the_same_timeline(tmp_path):
    """A human re-cutting a take by editing focus/hold events and
    re-running the composer needs no re-recording -- exercised here by
    composing the same timeline twice and getting the same duration."""
    take_dir = tmp_path / "take"
    take_dir.mkdir()
    make_clip(take_dir / "observer.webm", 4.0)
    timeline = Timeline.new("observer.webm")
    timeline.save(take_dir / "timeline.json")

    first = compose(take_dir, output=take_dir / "first.webm")
    second = compose(take_dir, output=take_dir / "second.webm")
    assert ffprobe_duration(first) == pytest.approx(ffprobe_duration(second), abs=0.1)


@requires_ffmpeg
def test_compose_uses_every_turns_own_clip_for_a_repeated_actor(tmp_path, monkeypatch):
    """(regression, PR #14 review finding #2, reproduced) The composer used
    to build `clip_by_actor`/`starts`/`ends` as dicts keyed by actor name,
    so an actor with more than one turn -- "reception" ×3 in
    contact_form.robot, "manager"/"reviewer3" ×2 in the other two stories --
    silently dropped every earlier turn's clip and timing to its last one,
    and every earlier clip file was never even added to ffmpeg's inputs.
    Here "reception" plays two turns, each with its own clip file; assert
    both actually reach ffmpeg's input list."""
    take_dir = tmp_path / "take"
    take_dir.mkdir()
    make_clip(take_dir / "observer.webm", 8.0)
    make_clip(take_dir / "reception-1.webm", 2.0, color="red")
    make_clip(take_dir / "reception-2.webm", 2.0, color="green")

    timeline = Timeline.new("observer.webm")
    timeline.add_actor_clip("reception", "reception-1.webm", offset=0.0, duration=2.0)
    timeline.add_event({"type": "turn_start", "time": 0.0, "actor": "reception"})
    timeline.add_event({"type": "turn_end", "time": 2.0, "actor": "reception"})
    timeline.add_actor_clip("reception", "reception-2.webm", offset=6.0, duration=2.0)
    timeline.add_event({"type": "turn_start", "time": 6.0, "actor": "reception"})
    timeline.add_event({"type": "turn_end", "time": 8.0, "actor": "reception"})
    timeline.save(take_dir / "timeline.json")

    captured = {}

    def fake_ffmpeg(*args, capture=True):
        captured["args"] = args
        Path(args[-1]).write_bytes(b"")

    monkeypatch.setattr(compose_module, "ffmpeg", fake_ffmpeg)
    compose(take_dir)

    rendered = " ".join(str(arg) for arg in captured["args"])
    assert "reception-1.webm" in rendered
    assert "reception-2.webm" in rendered


@requires_ffmpeg
def test_compose_uses_a_focus_events_own_border_not_the_default(tmp_path, monkeypatch):
    """(regression, PR #14 review finding #11) pad_inset() always used the
    module-level DEFAULT_BORDER constant -- a focus event's own `border`
    value was resolved by _view_at() and unpacked by every caller, but
    never actually passed into pad_inset()."""
    take_dir = tmp_path / "take"
    take_dir.mkdir()
    make_clip(take_dir / "observer.webm", 4.0)
    make_clip(take_dir / "author.webm", 2.0, color="red")

    timeline = Timeline.new("observer.webm")
    timeline.add_actor_clip("author", "author.webm", offset=1.0, duration=2.0)
    timeline.add_event({"type": "turn_start", "time": 1.0, "actor": "author"})
    timeline.add_event(
        {
            "type": "focus",
            "time": 1.0,
            "view": "actor",
            "scale": 0.4,
            "margin": 24,
            "border": 9,
        }
    )
    timeline.add_event({"type": "turn_end", "time": 3.0, "actor": "author"})
    timeline.save(take_dir / "timeline.json")

    captured = {}

    def fake_ffmpeg(*args, capture=True):
        captured["args"] = args
        Path(args[-1]).write_bytes(b"")

    monkeypatch.setattr(compose_module, "ffmpeg", fake_ffmpeg)
    compose(take_dir)

    filter_complex = captured["args"][captured["args"].index("-filter_complex") + 1]
    assert "pad=iw+18:ih+18:9:9:" in filter_complex
    assert f"pad=iw+{2 * compose_module.DEFAULT_BORDER}:" not in filter_complex


@requires_ffmpeg
def test_compose_with_actor_focus_lingering_past_turn_end_freezes_instead_of_breaking(
    tmp_path,
):
    """(regression) A story that sets `Focus actor` and never flips it back
    before the turn's own `[Teardown] End Actor Turn` -- e.g. deliberately
    ending a take on the actor's own last frame -- leaves the gap after
    `turn_end` still resolving to "actor" (see
    test_gap_focus_event_can_bring_back_the_actor, a pure-_view_at test
    covering exactly this). But the main per-boundary loop's
    `if view == "actor":` branch called turn_slice() unconditionally, with
    no `turn_end` clamp -- unlike the observer-main/actor-inset branch just
    below it, which already guards this exact case (`if end <= turn_end:
    turn_slice() else: frozen_turn_slice()`). Past `turn_end`,
    turn_slice()'s own `rel_start` (clamped to `clip["duration"]`) can land
    at or past `rel_end`, handing ffmpeg's trim filter a backwards/empty
    range -- which silently produced a near-zero-length segment, chopping
    real seconds off the composed output instead of showing a frozen frame
    the way the inset branch already does."""
    take_dir = tmp_path / "take"
    take_dir.mkdir()
    make_clip(take_dir / "observer.webm", 6.0, color="blue")
    make_clip(take_dir / "author.webm", 2.0, color="red")

    timeline = Timeline.new("observer.webm")
    timeline.add_actor_clip("author", "author.webm", offset=1.0, duration=2.0)
    timeline.add_event({"type": "turn_start", "time": 1.0, "actor": "author"})
    timeline.add_event(
        {
            "type": "focus",
            "time": 3.0,
            "view": "actor",
            "scale": 0.4,
            "margin": 24,
            "border": 3,
        }
    )
    timeline.add_event({"type": "turn_end", "time": 3.0, "actor": "author"})
    timeline.save(take_dir / "timeline.json")

    output = compose(take_dir)
    # No chapters/non-recorded holds in this timeline: the composed
    # output's duration must equal the observer's own -- a broken trim on
    # the [3.0, 6.0) gap segment would have come up short instead.
    assert ffprobe_duration(output) == pytest.approx(6.0, abs=0.5)
    # Well past the turn (and the actor clip's own 2.0s of real footage):
    # still showing the actor, frozen on its last frame, as the main view
    # (top-left is free of any inset in this minimal setup -- the engine's
    # own observer-as-inset default sits bottom-right).
    assert is_color(corner_pixel(output, 5.0, "top-left"), "red")


@requires_ffmpeg
def test_compose_rejects_overlapping_turns(tmp_path):
    take_dir = tmp_path / "take"
    take_dir.mkdir()
    make_clip(take_dir / "observer.webm", 6.0)
    make_clip(take_dir / "a.webm", 3.0, color="red")
    make_clip(take_dir / "b.webm", 3.0, color="green")

    timeline = Timeline.new("observer.webm")
    timeline.add_actor_clip("a", "a.webm", offset=0.0, duration=3.0)
    timeline.add_actor_clip("b", "b.webm", offset=1.0, duration=3.0)
    timeline.add_event({"type": "turn_start", "time": 0.0, "actor": "a"})
    timeline.add_event({"type": "turn_end", "time": 3.0, "actor": "a"})
    timeline.add_event({"type": "turn_start", "time": 1.0, "actor": "b"})
    timeline.add_event({"type": "turn_end", "time": 4.0, "actor": "b"})
    timeline.save(take_dir / "timeline.json")

    with pytest.raises(ComposeError):
        compose(take_dir)


@requires_ffmpeg
def test_compose_refuses_unknown_timeline_version(tmp_path):
    take_dir = tmp_path / "take"
    take_dir.mkdir()
    make_clip(take_dir / "observer.webm", 2.0)
    timeline = Timeline.new("observer.webm")
    timeline.save(take_dir / "timeline.json")
    import json

    data = json.loads((take_dir / "timeline.json").read_text())
    data["version"] = 1
    (take_dir / "timeline.json").write_text(json.dumps(data))

    with pytest.raises(Exception):  # noqa: B017 -- TimelineError from Timeline.load
        compose(take_dir)


def test_output_time_is_unchanged_with_nothing_inserted_before_it():
    assert _output_time(5.0, [], []) == pytest.approx(5.0)


def test_output_time_accounts_for_a_chapter_inserted_before_it():
    chapters = [{"time": 1.0, "duration": 2.0}]
    # A caption at raw time 5.0 sits after the title card, so the card's
    # whole 2.0s is added to where it actually lands in the output.
    assert _output_time(5.0, chapters, []) == pytest.approx(7.0)


def test_output_time_ignores_a_chapter_that_comes_after_it():
    chapters = [{"time": 6.0, "duration": 2.0}]
    assert _output_time(5.0, chapters, []) == pytest.approx(5.0)


def test_output_time_ignores_a_recorded_hold():
    """(mirrors predicted_duration()'s own "recorded" hold exclusion) A
    "recorded" hold adds no synthetic freeze segment, so it must not shift
    a caption's mapped time either."""
    holds = [{"time": 1.0, "duration": 3.0, "recorded": True}]
    assert _output_time(5.0, [], holds) == pytest.approx(5.0)


def test_write_captions_vtt_orders_cues_by_time_regardless_of_input_order(tmp_path):
    captions = [
        {"time": 5.0, "text": "second", "duration": 2.0},
        {"time": 1.0, "text": "first", "duration": 2.0},
    ]
    vtt_path = write_captions_vtt(tmp_path / "output.vtt", captions, [], [])
    text = vtt_path.read_text()
    assert text.startswith("WEBVTT")
    assert text.index("first") < text.index("second")


@requires_ffmpeg
def test_compose_with_captions_writes_a_vtt_sidecar_accounting_for_the_title_card(
    tmp_path,
):
    """(issue #19 acceptance criteria) A toy take with two captions --
    one before a turn's title card, one during the turn -- produces a
    valid output.vtt whose cue times account for the title card inserted
    before the turn."""
    take_dir = tmp_path / "take"
    take_dir.mkdir()
    make_clip(take_dir / "observer.webm", 3.0)
    make_clip(take_dir / "author.webm", 1.0, color="red")

    timeline = Timeline.new("observer.webm")
    timeline.add_actor_clip("author", "author.webm", offset=0.5, duration=1.0)
    timeline.add_event(
        {"type": "caption", "time": 0.0, "text": "Before", "duration": 0.5}
    )
    timeline.add_event({"type": "turn_start", "time": 0.5, "actor": "author"})
    timeline.add_event(
        {
            "type": "chapter",
            "time": 0.5,
            "eyebrow": "Story",
            "title": "Author",
            "subtitle": "Doing a thing",
            "duration": 2.0,
        }
    )
    timeline.add_event(
        {"type": "caption", "time": 1.0, "text": "During", "duration": 0.5}
    )
    timeline.add_event({"type": "turn_end", "time": 1.5, "actor": "author"})
    timeline.save(take_dir / "timeline.json")

    output = compose(take_dir)
    vtt_path = output.with_suffix(".vtt")
    assert vtt_path.exists()

    cues = parse_vtt_cue_times(vtt_path)
    assert len(cues) == 2
    # "Before" (raw 0.0s) sits ahead of the title card (time=0.5), so it is
    # unaffected by it.
    assert cues[0] == pytest.approx((0.0, 0.5), abs=0.01)
    # "During" (raw 1.0s) sits after the title card, so its 2.0s is added.
    assert cues[1] == pytest.approx((3.0, 3.5), abs=0.01)
    output_duration = ffprobe_duration(output)
    assert cues[1][1] <= output_duration + 0.5
